services:
  - type: web
    name: faceless-video-platform
    runtime: node
    plan: free
    region: frankfurt
    rootDir: nextjs_space
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: ELEVENLABS_API_KEY
        sync: false
      - key: PIXABAY_API_KEY
        sync: false
